import type { Metadata } from "next";
import { Karla, Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/layout/Navbar";
import SubMenu from "@/components/layout/SubMenu";
import Footer from "@/components/layout/Footer";

const karla = Karla({
  variable: "--font-karla",
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "600", "700", "800"]
});

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700"]
});

export const metadata: Metadata = {
  title: "PASCI",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${karla.variable} ${poppins.variable} antialiased`}>
      <body>
        <Navbar />
        <SubMenu />
        {children}
        <Footer />
      </body>
    </html>
  );
}
